version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

formats:
    - epub

sphinx:
  configuration: docs/CN/source/conf.py

python:
  install:
    - requirements: docs/CN/requirements-docs.txt